### ISSUE TITLE
IBM K8S Doccano Auth Problem

### ISSUE THREAD

**Issue by matiaspierri** [doccano/doccano#1354]
# IBM K8S AUTH PROBLEM

I have worked with doccano in my local computer using docker and setting the env variable with the command line, but when i am trying a Kubernetes environment and setting the envs variables using a YAML file doccano doesn't recognize the Default User.

My envs in the deployment.yaml look like this
```
env:
- name: ADMIN_USERNAME
  value: "admin"
- name: ADMIN_EMAIL
  value: "admin@example.com"
- name: ADMIN_PASSWORD
  value: "password"
```
But i get this error
![image](https://user-images.githubusercontent.com/79118289/117684431-5e900780-b18b-11eb-95aa-446bd459ed2f.png)

If you need more information about the issue please let me know because i am new in this community
