### ISSUE TITLE
Username of superuser is not customizable 

### ISSUE THREAD

**Issue by sstamatiadis-dlt** [doccano/doccano#2312]
How to reproduce the behaviour

Dear maintainers,

First of all thank you for your efforts!

I think I have spotted a bug. I did not find any information in the issues or the guides.
It seems like there is an environment variable that allows to set the username of the administrator (default is "admin") but I am not sure if it actually works.

I deploy the image on AWS EKS through the most relatable Helm chart I could find.

1. I specify the environment through the helm values.yaml
2. The deployment manifest seems to be passing the value correctly
3. When I enter the app or admin panel login form it is only when I input 'admin' as a username, instead of "Administrator" that I use.
---------

Part of the Helm generated deployment manifest

```YAML
containers:
    - name: doccano
      image: doccano/doccano:1.8.0
      args:
        - /bin/bash
        - /config/bootstrap.sh
      ports:
        - name: 8000tcp
          containerPort: 8000
          protocol: TCP
      env:
        - name: ADMIN_EMAIL
          value: example@example.com
        - name: ADMIN_USERNAME
          value: Administrator
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doccano-password
              key: ADMIN_PASSWORD
              optional: false
        - name: DATABASE_URL
          value: >-
            postgres://doccano:XXXXXXXXXXXX@doccano-xxxxxxxxx-postgresql:5432/doccano?sslmode=disable
```

Your Environment
---------

*   Operating System: **AWS EKS managed node linux AMI**
*   Python Version Used: **ENV PYTHON_VERSION=3.8.12** - According to docker image [doccano/doccano:1.8.0](https://hub.docker.com/layers/doccano/doccano/1.8.0/images/sha256-220c119c47aade6cff24c2ccd235370313477215e8270493526e4feba9b51731?context=explore) 
*   When you install doccano: Not sure what is meant here
*   How did you install doccano (Heroku button etc): Helm Chart https://artifacthub.io/packages/helm/curie-df-helm-charts/doccano
