### ISSUE TITLE
Persistence path for Kubernetes?

### ISSUE THREAD

**Issue by harshmanvar** [doccano/doccano#648]
I have set up Postgres in Kubernetes and also setup Doccano in Kubernetes however it's working well but wants to know the mount point for Kubernetes to attach Persistence volume.

My deployment.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: doccano
  name: doccano
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: doccano
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: doccano
        tier: frontend
    spec:
      containers:
      - env:
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_EMAIL
          value: harsh.manvar@xxxxx.com
        - name: ADMIN_PASSWORD
          value: admin
        - name: DATABASE_URL
          value: postgres://root:2lnhK06u@postgres:5432/doccano?sslmode=disable
        - name: ALLOW_SIGNUP
          value : "True"
        image: doccano/doccano
        volumeMounts:
        - name: doccano-data
          mountPath: app/staticfiles
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 128Mi
        name: doccano
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 80
          name: https
          protocol: TCP
      volumes:
      - name: doccano-data
        persistentVolumeClaim:
          claimName: doccano-data
```

right now i have used path : `app/staticfiles` but when pod restarts it delete all the files inside it that means files are not persistent at this path.
