### ISSUE TITLE
Clarify how to set port using docker-compose.prod.yml

### ISSUE THREAD

**Issue by andreizolotarev** [doccano/doccano#805]
Hi everyone!
I want to set port for doccano, for example 7777, so I will be able to reach it at 0.0.0.0:7777 instead of 0.0.0.0/.
I would like to ask anyone who has successfully set port with docker-compose.prod.yml to describe how you've done it.
Thank you!

**Comment by harmw** [comment]
```
nginx:
    build: ./nginx
    volumes:
      - www:/var/www/html:ro
      - static_volume:/static
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - network-frontend
```

This is the `nginx` proxy config to listen on port `80` and do forwarding to _container-port 80_. Changing this to read `7777:80` should be all you need.
Alternatively, you can also reconfigure nginx to open a listener on a different port, but since that's all abstracted in compose I wouldn't do that.
