### ISSUE TITLE
Docker Compose fails when behind a corporate proxy (Network resolution error inside container)

### ISSUE THREAD

**Issue by PATELS2R** [doccano/doccano#983]
I am facing issues while using `docker-compose -f docker-compose.dev.yml up`
I am behind a corporate proxy. When executing docker-compose up command, it is able to download the required images. However when the container gets started and the setup commands are executed, I get `could not resolve deb.debian.org` and `unable to look for github.com` errors.

I suspect that I was able to download the images because that happened at host level. However the proxy configuration doesn't seem correct inside container. 

I refereed this [link](https://docs.docker.com/network/proxy/) for proxy setup, however I am on docker v1.13.1 (organizational restrictions) with docker-compose version v1.27. So the only option for me was to set `HTTP_PROXY` env variable at host level. I also updated the docker-compose.dev.yml to have following changes
```
environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
      HTTP_PROXY: "http://proxy.eu.novartis.net:2010/"
      HTTPS_PROXY: "http://proxy.eu.novartis.net:2010/"
```

However I am still facing the same issue. i.e. Network resolution error while container setup.
